#!/usr/bin/env python3
# Generates src/aafont.h -- anti-aliased (8-bit grayscale coverage) glyph data for the clock
# effect, rendered from JetBrains Mono Bold (SIL Open Font License, tools/JetBrainsMono-Bold.ttf).
# Two faces: BIG (HH:MM) and SMALL (seconds + MM/DD date). The renderer scales the ink colour by
# each pixel's coverage, so the digits have smooth edges on the panel's colour channels.
#
# Needs Pillow:  python3 -m venv venv && venv/bin/pip install Pillow
# Run from the project root:  venv/bin/python tools/genaafont.py
from PIL import Image, ImageDraw, ImageFont

TTF = "tools/JetBrainsMono-Bold.ttf"
OUT = "src/aafont.h"
BIG_PX, BIG_CH = 40, "0123456789:"       # HH:MM on tall panels
MED_PX, MED_CH = 20, "0123456789:"       # HH:MM:SS on short (128x32) panels
SMALL_PX, SMALL_CH = 13, " /:0123456789" # seconds + MM/DD date

def render_face(px, chars):
    fnt = ImageFont.truetype(TTF, px)
    asc, desc = fnt.getmetrics()
    baseline = asc + 4
    glyphs, cov = {}, bytearray()
    for ch in chars:
        adv = round(fnt.getlength(ch))
        canvas = Image.new("L", (px * 2 + 16, asc + desc + 16), 0)
        ImageDraw.Draw(canvas).text((6, baseline), ch, fill=255, font=fnt, anchor="ls")
        bb = canvas.getbbox()
        if bb is None:                       # blank glyph (space)
            glyphs[ch] = (0, 0, 0, 0, adv, 0); continue
        l, t, r, b = bb
        crop = canvas.crop((l, t, r, b))
        off = len(cov); cov += crop.tobytes()
        glyphs[ch] = (crop.width, crop.height, l - 6, t - baseline, adv, off)
    return {"asc": asc, "lineH": asc + desc, "glyphs": glyphs, "cov": cov, "chars": chars}

def emit(f, name, face):
    cov, chars = face["cov"], face["chars"]
    f.write(f"static const uint8_t {name}_COV[{len(cov)}] = {{{','.join(map(str, cov))}}};\n")
    f.write(f"static const AAGlyph {name}_G[{len(chars)}] = {{\n")
    for ch in chars:
        w, h, xo, yo, adv, off = face["glyphs"][ch]
        f.write(f"  {{{w},{h},{xo},{yo},{adv},{off}}}, // {'space' if ch==' ' else repr(ch)}\n")
    f.write("};\n")
    idx = [255] * 128
    for i, ch in enumerate(chars):
        idx[ord(ch)] = i
    f.write(f"static const uint8_t {name}_IDX[128] = {{{','.join(map(str, idx))}}};\n")
    f.write(f"static const AAFont {name} = {{ {face['asc']}, {face['lineH']}, "
            f"{name}_G, {name}_COV, {name}_IDX }};\n\n")

big = render_face(BIG_PX, BIG_CH)
med = render_face(MED_PX, MED_CH)
small = render_face(SMALL_PX, SMALL_CH)
with open(OUT, "w") as f:
    f.write("// aafont.h -- GENERATED by tools/genaafont.py; do not edit by hand.\n"
            "// Anti-aliased glyph coverage from JetBrains Mono Bold (SIL Open Font License).\n"
            "// BIG = HH:MM, SMALL = seconds + MM/DD date. Coverage is 8-bit; the clock renderer\n"
            "// scales the ink colour by it, so edges stay smooth on the panel's colour channels.\n"
            "#pragma once\n#include <stdint.h>\n\n"
            "struct AAGlyph { uint8_t w, h; int8_t xoff, yoff; uint8_t adv; uint16_t off; };\n"
            "struct AAFont  { uint8_t asc, lineH; const AAGlyph* g; const uint8_t* cov; const uint8_t* idx; };\n\n")
    emit(f, "AAFONT_BIG", big)
    emit(f, "AAFONT_MED", med)
    emit(f, "AAFONT_SMALL", small)
print(f"wrote {OUT}: BIG {len(big['cov'])}B, MED {len(med['cov'])}B, SMALL {len(small['cov'])}B")
